### ISSUE TITLE
Feature Request: onRenderComplete

### ISSUE THREAD

**Issue by alexanderstier** [jweiland-net/infinitescrolling#1]
Hi,

the embedded jquery-ias.js library supports some functions on defined states of the XHR loading process. The onRenderComplete function lets you process the loaded items of e.g. a news list after they are added to the container.

Is there a reason, why this function(s) is(are) not available through the constants?
What do you think about adding these to the extension?

Kind regards
Alexander

**Comment by froemken** [comment]
Hello @RacingTomcat 

the constants editor does not allow textarea input fields.
If you want to add onRenderComplete to ias options please use setup TS like:

```
page.jsInline.20.120 = TEXT
page.jsInline.20.120.value (
  onRenderComplete: function([params]) {
    // do what you want
  }
)
```
