### ISSUE TITLE
Link to manual in TER not working

### ISSUE THREAD

**Issue by Starraider** [jweiland-net/infinitescrolling#12]
The Link to the "External Manual" in [TER](https://extensions.typo3.org/extension/infinitescrolling) leads to a [404 page](https://docs.typo3.org/typo3cms/extensions/infinitescrolling/stable/).

**Comment by froemken** [comment]
Good morning @Starraider 

thank for for that hint. I just have updated the link in TER to:

https://docs.typo3.org/p/jweiland/infinitescrolling/master/en-us/

Hmmm, the link in detail view was correct now, but in TER search results it's still wrong:
https://extensions.typo3.org/?L=0&id=1&tx_solr%5Bq%5D=infinitescrolling

Let us wait some minutes, maybe the solr scheduler was not started until now.

Stefan
