### ISSUE TITLE
TYPO3 v8: Unsupported page propertie page.includeJSlibs

### ISSUE THREAD

**Issue by metiny** [jweiland-net/infinitescrolling#2]
Hello Stefan,

with TYPO3 8 page.includeJSlibs has been removed. Now there is page.includeJSLibs, with large L.

Configuration/TypoScript/setup.txt

Best regards
Metin

**Comment by froemken** [comment]
Hello @metiny 

Thank you for that hint. We have just uploaded a nearly complete new version of infinitescrolling. We have updated IAS library to 2.2.3 and have moved all JS libs to Footer. So the problem with with "L" was also solved.

Hope you have fun with the new version.

Stefan
