### ISSUE TITLE
Bug in loading previous items

### ISSUE THREAD

**Issue by DJCrispyRice** [jweiland-net/infinitescrolling#8]
Hi,
I am using your extension in this environment : 
Typo3 9.5.14
News 7.3.1 (with my own extension on top of it)
Infinite Scrolling 3.0.0

Here is my TS configuration : 

```
plugin.tx_infinitescrolling {
    includeJQueryLibrary = 0
    container = div.articles
    item = .article-wrapper
    pagination = div.page-navigation
    next = li.next a
    previous = li.previous a
    negativeMargin = 100
    offset = 100
    loader.html = (a loader)
    nextItems.html = (non relevant)
}
```

I have a main page that contains 3 blocks : a menu, some news that are highlighted (height may vary) and a list of every other news. On every pagebreak, the URL changes. So if I scroll down to the first pagebreak (i.e loading the second page), the URL changes to xxx/2. If I scroll back to page 1, the URL reverts to xxx. If I reload while the URL is xxx/5, it loads items relative to page 5. By scrolling down, I get page 6 loaded. If I want content from page 4, I have to click a "load previous" button to get it.

I discovered that when you mix loading a new page (scroll down) and clicking the previous button, the pagebreaks get confused resulting on jumps between pages. Here is a debug of the pagebreak array that should illustrate what is wrong : 

> 
> 0: Array [ 0, "/fr/magazine/3" ]
> ​
> 1: Array [ 4186.699951171875, "/fr/magazine/4" ]
> ​
> 2: Array [ 9655.699951171875, "/fr/magazine/5" ]
> ​
> 3: Array [ 10144.699951171875, "/fr/magazine/6" ]
> ​
> 4: Array [ 11536.699951171875, "/fr/magazine/7" ]
> ​
> 5: Array [ 10570, "/fr/magazine/8" ]

​I started by loading page 4 (/fr/magazine/4). I loaded page 5, 6, 7 by scrolling down, 3 (previous button) and finally 8. The result is that page 4 is really long, 5 and 6 are short and 7 is not reachable, it jumps directly to 8.

By investigating the code, I found the Paging.js file, especially the onPrev function. On every load of a previous page, it recalculates the pagebreaks using this formula : 

```
this.pagebreaks.unshift([0, url]);
for (var i = 1, l = self.pagebreaks.length; i < l; i++) {
self.pagebreaks[i][0] = self.pagebreaks[i][0] + $firstItem.offset().top;
}
```

I think the issue remains on the using of $firstItem.offset().top. In my case, it doesn't work because I have other blocks before the infinite scrolling one. I suggest that only the first index is based on this variable (so that the first "page" starts from the top of the page) but I have no further idea for a better handling of this. It also seems there is an issue in the onNext function because I observed this : 

> 0: Array [ 0, "/fr/magazine/4" ]
> ​
> 1: Array [ 5469, "/fr/magazine/5" ]
> ​
> 2: Array [ 5958, "/fr/magazine/6" ]
> ​
> 3: Array [ 7350, "/fr/magazine/7" ]

By starting from 4 and loading 5, 6 and 7. Unfortunatly I wasn't able to replicate what I did exactly. I should also mention that replicating the same steps results most frequently to an issue but it can vary somehow (coordinates are never the same). I guess it is because of the var currentScrollOffset = this.ias.getCurrentScrollOffset(this.ias.$scrollContainer); (I don't always scroll the same way, sometimes I start loading a page and then scroll up and come back to it later...). Since I work on a dev environment, I also disable all of the typo caches so loading can take a dozen seconds. 

I hope the issue is clear enough. Don't hesitate to ask any info you need to investigate, I would happily help as I can. 

Thank you ! 

Regards,

**Comment by froemken** [comment]
Hello @DJCrispyRice 

It seems that there is a bug within the IAS Script. As we are not the developers of the contained JS, we can not solve the problem and we can not update to the newest IAS release as this cost money: https://infiniteajaxscroll.com/pricing
So please open a new issue ticket here: https://github.com/webcreate/infinite-ajax-scroll
